//////////// == CONTROL STRUCTURES: DATA == ////////////


~findABetterWayToAccess = (

	henriette: (
		silenceThresh: -20.dbamp,
		minFreq: 60.midicps,
		maxFreq: 84.midicps,
		// all sorts of stuff can go here...compressor settings?amplitude threshold?
	),
	camilla: (),
	maria: (),
	sigrid: (),
	tina: (),

	richard: (),
	lyder: (),
	tancred: (),

	andreas: (),
	magnus: (),
	johannes: (),

	knut: (),
	arneMartin: (),
	alexander: (),
	oskar: (),

)

